### ISSUE TITLE
Everything explicit is better than implicit 💥💥💥

### ISSUE THREAD

**Issue by budarin** [valtiojs/use-valtio#3]
declaration of dependencies is much better than auto tracked behavior

**Comment by dai-shi** [comment]
Though, it's pretty limited, and in some cases, render is not optimized.
In general, many people seem to like `useSnapshot`'s tracking behavior.

That said, I might be considering non-tracking hook for the future version of Valtio (probably v3 after v2), for some reasons.

I think you'd prefer Zustand to Valtio, for "more explicit".

**Comment by budarin** [comment]
What are the limits and in which cases the rendering may not be optimal?

My experience has confirmed the phrase from the title a thousand times - it is better to explicitly declare what you expect than to search for a long time for what went wrong because something does not work clearly and not as you expect but works implicit.

I used Zustand corny because I didn't know that you had developed so many different state managers! :)

Now I'm looking at Valtio and trying to figure out what problems it will bring me when switching from Zustand

I like 3 things in Valtio
- there is no useless calling thousands of selectors with checks to change them
- there is no torment with changing the immutable state
- there is no immer )

**Comment by dai-shi** [comment]
> What are the limits and in which cases the rendering may not be optimal?

```js
const snap = useSnapshot(state);
const value = snap.a ? snap.b : snap.c;
```
This is one case, which is not possible to optimize with `use-valtio`.

**Comment by budarin** [comment]
But does use-valtio use dependency declaration!?

 ```js
 const snap = use-valtio(state, ['a', 'b', 'c']);
 const value = snap.a ? snap.b : snap.c;
 ```

Or am I wrong?

**Comment by budarin** [comment]
Explicit declaration will also help to get rid of refs in the store- refs is not natural

**Comment by dai-shi** [comment]
> const value = snap.a ? snap.b : snap.c;

if `a` is true, we shouldn't track `c`.

**Comment by budarin** [comment]
yes, this can be a problem!
can we use an additional helper function similar to the selector in such cases?

```ts
const snap = use-valtio(state, ['a', 'b', 'c'], state => state.a ? state.b : state.c);
```

**Comment by dai-shi** [comment]
That's an easy problem. Many complex examples would exist.
We also need to assume heavy computation.
```js
const value = someHeavyComputation(snap.a) ? ... : ...
```

I mean, I would like to find a nice solution (can be implicit, maybe prefer implicit) for the future Valtio, but needs more research about it.

Thanks for ideating it!
